/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.jakobeks.wisielec;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferStrategy;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jacob
 */
public class Frame extends javax.swing.JFrame {

    public List<pytanie> q = new ArrayList();
    public int qNum  = 0;
    public int poprawne = 0;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        for(int i = 0; i<21; i++) 
            q.add(new pytanie());
        set(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wisielec by Jakub Lechocki");
        setResizable(false);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton1");

        jTextPane1.setEditable(false);
        jTextPane1.setText("Asdf");
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Kolejne");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Resetuj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        canvas1.setMinimumSize(new java.awt.Dimension(100, 100));
        canvas1.setName("");
        canvas1.setPreferredSize(new java.awt.Dimension(214, 194));

        jLabel1.setText("Poprawnie ");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(qNum <q.size()-1){
            sprawdz(qNum );
            set(qNum);
        } else 
            end();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        q = new ArrayList();
        qNum = 0;
        poprawne = 0;
    
        for(int i = 0; i<21; i++) 
            q.add(new pytanie());
        set(0);
        draw(0);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);               
        jRadioButton4.setEnabled(true); 
        jButton1.setEnabled(true);

        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    
    public void set(int licznik) {
        jTextPane1.setText(q.get(licznik).tresc);
        jRadioButton1.setText("A) "+q.get(licznik).odpowiedzi[0]);
        jRadioButton1.setSelected(true);
        jRadioButton2.setText("B) "+q.get(licznik).odpowiedzi[1]);
        jRadioButton3.setText("C) "+q.get(licznik).odpowiedzi[2]);
        jRadioButton4.setText("D) "+q.get(licznik).odpowiedzi[3]);
        
        jLabel2.setText(poprawne+"/"+qNum );

    }
    
    public void sprawdz(int licznik) {
        if(q.get(licznik).poprawna == 0 && jRadioButton1.isSelected())
            poprawne++;
        if(q.get(licznik).poprawna == 1 && jRadioButton2.isSelected())
            poprawne++;
        if(q.get(licznik).poprawna == 2 && jRadioButton3.isSelected())
            poprawne++;
        if(q.get(licznik).poprawna == 3 && jRadioButton4.isSelected())
            poprawne++;
        qNum ++;
        draw(qNum  - poprawne);
    }
    
    private void end() {
       jRadioButton1.setEnabled(false);
       jRadioButton2.setEnabled(false);
       jRadioButton3.setEnabled(false);               
       jRadioButton4.setEnabled(false); 
       jButton1.setEnabled(false);
    }
    
    public void draw(int i) {
        BufferStrategy bs = canvas1.getBufferStrategy();
        Graphics g = canvas1.getGraphics();
        
        g.setColor(new Color(214, 217, 223));
        g.fillRect(0, 0, canvas1.getWidth(), canvas1.getHeight());
        
        if(i > 9) {
            g.setColor(new Color(150, 50, 50));
            g.fillRect(135, 6, 5, 40);
            end();
        }
        
        g.setColor(new Color(30, 30, 30));
        if(i > 0) {
            g.fillRect(5, 5, 14, 190);
        }
        if(i > 1) {
            g.fillRect(5, 5, 135, 14);
        }
        if(i > 2) {
            g.fillPolygon(new int[] {5, 55, 65, 5}, new int[] {55, 5, 5, 65}, 4);
        }
        if(i > 3) {
            g.fillOval(120, 35, 25, 35);
        }
        if(i > 4) {
            g.fillRect(130, 65, 4, 65);
        }
        if(i > 5) {
            g.fillPolygon(new int[] {132, 155, 155, 132}, new int[] {120, 200, 210, 130}, 4);
        }
        if(i > 6) {
            g.fillPolygon(new int[] {131, 111, 111, 131}, new int[] {120, 200, 210, 130}, 4);
        }
        if(i > 7) {
            g.fillPolygon(new int[] {132, 155, 155, 132}, new int[] {75, 125, 135, 80}, 4);
        }
        if(i > 8) {
            g.fillPolygon(new int[] {131, 111, 111, 131}, new int[] {75, 125, 135, 80}, 4);
        }
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
